[tools]
neovim = "latest"
python = "latest"
uv = "latest"
bat = "latest"
fzf = "latest"
lsd = "latest"

[settings]
python.uv_venv_auto = true
idiomatic_version_file_enable_tools = ["python"]
experimental = true

[env]
APP_REPO = 'study-app'
GITOPS_REPO = 'study-app-gitops'
